// AUTO-GENERATED by scripts/write-git-version.mjs — do not edit manually.
// Commit this file so Docker builds (which exclude .git) always have version info.
export const GIT_COMMIT_HASH = "7093718";
export const GIT_COMMIT_TIME = "2026-09-13T00:39:44+01:00";
