// AUTO-GENERATED by scripts/write-git-version.mjs — do not edit manually.
// Commit this file so Docker builds (which exclude .git) always have version info.
export const GIT_COMMIT_HASH = "6c4f46bc";
export const GIT_COMMIT_TIME = "2026-10-09T03:57:12Z";
