// AUTO-GENERATED by scripts/write-git-version.mjs — do not edit manually.
// Commit this file so Docker builds (which exclude .git) always have version info.
export const GIT_COMMIT_HASH = "6a3834b";
export const GIT_COMMIT_TIME = "2026-09-20T22:03:41Z";
